export function historyPage() {
    const historyBtn = document.querySelector('#history')
    historyBtn.addEventListener('click', function(e) {
        e.preventDefault()
        document.querySelector('#pageContent').innerHTML= `<h1>A history of Mead</h1>
        <h2>How did it get to Thamesmead?</h2>
        <img src="https://images.unsplash.com/photo-1589711428882-6f8d7bff75f7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" style='height:450px;object-fit:contain'>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin hendrerit pulvinar vulputate. Pellentesque eget pellentesque arcu. Vestibulum accumsan sapien in mauris tempus condimentum. Mauris egestas neque est, non sagittis nisl fringilla id. Nam et sollicitudin dui, in convallis erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras nec imperdiet dolor, in dictum neque. Vivamus ultricies pretium imperdiet. Vestibulum at ligula eget diam semper placerat ut quis felis. Fusce nec sagittis ipsum. Sed suscipit velit leo, sit amet mollis quam hendrerit at. Ut vitae nisi quis odio condimentum pretium. Nulla in velit sit amet nisl eleifend vestibulum. Nullam rutrum magna in urna euismod cursus. Pellentesque a libero gravida erat iaculis vestibulum.</p></br>
        <img src="https://www.lesnesabbeywoods.org/wp-content/uploads/bb-plugin/cache/abbey-interior-e1612191352206-landscape-e79eb459ccf41d38bc5a91517ee37a16-5fbcfa33b4a05.jpg">
        <p>Integer facilisis porttitor sollicitudin. Integer commodo non est sed cursus. Praesent mattis est augue. Phasellus et viverra libero. Duis imperdiet urna id justo blandit pulvinar. Nunc ullamcorper tortor nec libero vehicula tristique. In blandit mi at nisi finibus laoreet. Vestibulum dolor felis, ultricies a tincidunt non, lobortis eget massa. In tincidunt et lacus nec maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vestibulum neque vel lorem pellentesque sagittis. Nam pellentesque turpis vel pulvinar rutrum.</p></br>
        <img src="https://www.historyhit.com/app/uploads/fly-images/5156778/Lesnes-Abbey-788x537.jpg">
        <p>Nullam malesuada sodales orci bibendum luctus. Sed consectetur, felis a blandit ultrices, metus urna aliquam elit, id elementum quam justo quis nulla. In eget blandit mi. Etiam bibendum, urna dignissim molestie porttitor, neque nunc vestibulum mauris, at pulvinar ipsum metus vel tortor. Sed nisl quam, fermentum mattis sapien sit amet, ultricies sollicitudin dolor. Donec sed lorem vel arcu vehicula tincidunt. Aenean et venenatis ex. Nunc libero felis, feugiat sed venenatis vel, placerat in mauris. In vestibulum massa ut augue tincidunt facilisis. Ut et vehicula risus, vitae posuere augue. Proin iaculis gravida neque ut pharetra. Maecenas eu arcu quis ante vestibulum maximus. Donec mollis nec ante ac commodo. Etiam sit amet eleifend metus, vitae dignissim quam. Suspendisse tristique lobortis urna, et molestie odio.</p>`
        })
}